# Generated by Django 4.2.6 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='Foto')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('date_project', models.DateField(verbose_name='Fecha del Proyecto')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observación')),
                ('link_github', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link GitHub')),
                ('link_website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Página Web')),
                ('is_work', models.BooleanField(verbose_name='Es Trabajo')),
                ('is_design', models.BooleanField(verbose_name='Es Diseño')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('skill', models.ManyToManyField(to='skill.skill', verbose_name='Lenguajes')),
            ],
            options={
                'verbose_name': 'Trabajo/Diseño',
                'verbose_name_plural': 'Trabajos/Diseños',
            },
        ),
    ]
