# Generated by Django 4.2.6 on 2023-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Foto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('skill', models.ManyToManyField(to='skill.skill', verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resumen',
            },
        ),
    ]
